In [2]:
import numpy as np
print(np.__version__)

1.20.3


In [3]:
my_list=[-17,0,4,5,9]
my_array_from_list = np.array(my_list)
my_array_from_list

array([-17,   0,   4,   5,   9])

In [4]:
my_array_from_list*10

array([-170,    0,   40,   50,   90])

In [5]:
my_tuple = (4,-3.45,5+7j)
my_tuple
my_array_from_tuple = np.array(my_tuple)
my_array_from_tuple

array([ 4.  +0.j, -3.45+0.j,  5.  +7.j])

#### Diff between python and numpy data structures

### Algorithm design techniques
*concern 1: producing the expected results
*concern 2: most optimal way?
*concern 3: how is it going to perform in larger datasets

#Constant time (O(1)) complexity

In [6]:
def getFirst(myList):
    return myList[0]

In [7]:
getFirst([1,2,3])

1

In [8]:
#Linear time (O(n)) complexity
def getSum(myList):
    sum = 0
    for item in myList:
        sum = sum + item
    return sum

In [9]:
getSum([1,2,3])

6

In [10]:
getSum([1,2,3,4,5])

15

In [1]:
#Quadratic time (O(n2)) complexity
def getSum(myList):
    sum = 0
    for row in myList:
        for item in row:
            sum += item
        return sum

In [2]:
getSum([[1,2],[3,4]])

3

In [21]:
getSum([[1,2,3],[4,5,6]])

6

In [9]:
#Logarithmic time (O(logn)) complexity
def searchBinary(myList, item):
    first = 0
    last = len(myList)-1
    foundFlag = False
    while (first <= last and not foundFlag):
        mid = (first + last)//2
        if myList[mid] == item :
            foundFlag = True
        else:
            if item < myList[mid]:
                last = mid - 1
            else:
                first = mid + 1
        return foundFlag

In [13]:
searchBinary([8,9,10,100,1000,2000,3000], 10)

False

In [14]:
A= 1
B= 2
C = A + B
C

3

In [15]:
bin_colors=['Red', 'Green', 'Blue', 'Yellow']
bin_colors[1]

'Green'

In [16]:
bin_colors[0:2]

['Red', 'Green']

In [17]:
bin_colors[:3]

['Red', 'Green', 'Blue']

In [18]:
bin_colors[3:]

['Yellow']

In [19]:
bin_colors[2:]

['Blue', 'Yellow']

In [20]:
bin_colors[:-1]

['Red', 'Green', 'Blue']

In [24]:
bin_colors=['Red',"Green", "Blue","Yellow"]
for aColor in bin_colors:
    print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [25]:
list(filter(lambda x:x > 100,[-5,200,300,-10,10,1000]))

[200, 300, 1000]

In [26]:
list(map(lambda x:x ** 2, [11,22,33,44,55]))

[121, 484, 1089, 1936, 3025]

In [27]:
list(map(lambda x:x+x**2,[11,22,33,44,55]))

[132, 506, 1122, 1980, 3080]

In [28]:
from functools import reduce
def doSum(x1,x2):
    return x1+x2
x = reduce(doSum,[100,122,33,4,5,6])

In [29]:
x = range(6)
x

range(0, 6)

In [1]:
oddNum = range(3,29,2)
oddNum

range(3, 29, 2)

In [2]:
bin_colors = {
    "manual_color" : "Yellow",
    "approved_color" : "Green",
    "refused_color" : "Red"
}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [3]:
bin_colors.get('approved_color')

'Green'

In [4]:
bin_colors['approved_color']

'Green'

In [5]:
bin_colors['approved_color']='Purple'

In [6]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [7]:
yellow = {'dandelions', 'fire hydrant', 'leaves'}
red = {'fire hydrant', 'blood', 'rose', 'leaves'}
yellow|red

{'blood', 'dandelions', 'fire hydrant', 'leaves', 'rose'}

In [8]:
yellow&red

{'fire hydrant', 'leaves'}

In [23]:
import pandas as pd
df = pd.DataFrame([['1','Fares', 32,True],
                 ['2', 'Elena', 23, False],
                 ['3','Steven', 40, True]])
df.columns = ['id', 'name','age','decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [3]:
df[2:3]

id    name  age decision
2  3  Steven   40     True

In [4]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [5]:
df[['id','age']]

id  age
0  1   32
1  2   23
2  3   40

In [6]:
df.iloc[:,3]

0     None
1    False
2     True
Name: decision, dtype: object

In [12]:
df.iloc[0:2,:]

id   name  age decision
0  1  Fares   32     None
1  2  Elena   23    False

In [13]:
df.iloc[1:3,:]

id    name  age decision
1  2   Elena   23    False
2  3  Steven   40     True

In [14]:
df.iloc[:,1:3]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [18]:
df[df.age==40]

id    name  age decision
2  3  Steven   40     True

In [20]:
df[df.decision!=True]

id   name  age decision
0  1  Fares   32     None
1  2  Elena   23    False

In [24]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

In [26]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [27]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [28]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [29]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [30]:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [31]:
print(type(myVector))

<class 'list'>


In [32]:
myVector = np.array([22,33,44,55])
print(myVector)
print(type(myVector))

[22 33 44 55]
<class 'numpy.ndarray'>
